### ISSUE TITLE
Intero compatibility

### ISSUE THREAD

**Issue by sarahzrf** [myfreeweb/intero.nvim#5]
Do you think it'd be possible to rewrite this to be compatible with vanilla Intero, or to try to get your server code merged into vanilla Intero? Building and managing separate packages is kind of a pain.

**Comment by valpackett** [comment]
No. Well, it's _possible_ to have a plugin that interacts with vanilla Intero, but it would suck. Having an RPC server is much, _much_ better than awkward console-editor interaction.

Why do you need separate packages? I just use this as the only Intero I have.

**Comment by sarahzrf** [comment]
Well, it's more about going out of the way to build something manually instead of being able to depend on it from Hackage or something - but it's not a huge deal.

**Comment by valpackett** [comment]
Why would you depend on a REPL? That sounds surprising. I think `git clone`, `cd` and `stack install` is fine for development tools.

**Comment by sarahzrf** [comment]
I should probably clarify that I've been trying out Nix, which means that there's some isolation between stuff installed in different contexts - so if I build-and-install a tool separately from a dev project, the tool can't necessarily see the packages installed for the project.

But this is probably not a common enough use case to really justify significant changes, I guess :)

Plus it's also probably a matter of my ineptness with Nix.

**Comment by dkasak** [comment]
It _would_ be nice if this was merged upstream, however. Did you ask chrisdone whether he'd consider it?
